import { test, expect, type Page } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
const sizes = [{ width: 1440, height: 900 }, { width: 1024, height: 768 }, { width: 768, height: 1024 }, { width: 390, height: 844 }]
async function noOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
}
async function shot(page: Page, name: string) {
  const directory = process.env.SCREENSHOT_DIR || 'verification/screenshots'
  await mkdir(directory, { recursive: true })
  await page.screenshot({ path: `${directory}/${process.env.BASE_URL ? 'live-' : ''}${name}.png`, fullPage: true, animations: 'disabled' })
}
for (const size of sizes) {
  test(`complete learning journey ${size.width}x${size.height}`, async ({ page }) => {
    await page.setViewportSize(size)
    const errors: string[] = []
    page.on('pageerror', e => errors.push(e.message))
    page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()) })
    await page.goto('./')
    await expect(page.getByRole('heading', { level: 1 })).toHaveText('화학삼투를 보기 전에')
    await noOverflow(page); await shot(page, `${size.width}-home`)
    await page.getByRole('link', { name: /세포호흡부터 보기/ }).click()
    await expect(page).toHaveURL(/#\/respiration$/)
    await noOverflow(page); await shot(page, `${size.width}-respiration`)
    for (const label of ['02 아세틸-CoA 생성', '03 TCA cycle', '04 전자전달계와 산화적 인산화']) {
      await page.getByRole('button', { name: label, exact: true }).click()
      await expect(page.getByRole('button', { name: label, exact: true })).toHaveAttribute('aria-pressed', 'true')
    }
    await expect(page.getByText('Complex II · H⁺ 펌프 아님', { exact: true })).toBeVisible()
    await noOverflow(page); await shot(page, `${size.width}-etc`)
    await page.getByRole('button', { name: '전자전달계에 전자 공급', exact: true }).click()
    await page.getByRole('button', { name: '막사이공간 (IMS)', exact: true }).click()
    await page.getByRole('button', { name: '전자를 Q에 전달하지만 H⁺를 펌프하지 않는다', exact: true }).click()
    await page.getByRole('button', { name: '✓ 세포호흡 학습 확인', exact: true }).click()
    await page.getByRole('link', { name: '다음 · 광합성 →', exact: true }).click()
    await expect(page).toHaveURL(/#\/photosynthesis$/)
    await noOverflow(page); await shot(page, `${size.width}-linear`)
    await page.getByRole('button', { name: '순환적 전자 흐름', exact: true }).click()
    await expect(page.getByText('PSII 미참여', { exact: true })).toBeVisible()
    await expect(page.getByText('NADPH 순생성 없음', { exact: true })).toBeVisible()
    await noOverflow(page); await shot(page, `${size.width}-cyclic`)
    await page.getByRole('button', { name: 'Calvin cycle', exact: true }).click()
    await expect(page.getByRole('img', { name: /Calvin cycle의 세 단계/ })).toBeVisible()
    await noOverflow(page); await shot(page, `${size.width}-calvin`)
    await page.getByRole('button', { name: 'PSII에서의 물 산화', exact: true }).click()
    await page.getByRole('button', { name: 'ATP', exact: true }).click()
    await page.getByRole('button', { name: '둘 다 사용된다', exact: true }).click()
    await page.getByRole('button', { name: '✓ 광합성 학습 확인', exact: true }).click()
    await page.getByRole('link', { name: '다음 · 화학삼투 탐색기 →', exact: true }).click()
    await page.getByRole('button', { name: '엽록체 틸라코이드', exact: true }).click()
    await expect(page.getByText('A · 틸라코이드 내강 · Thylakoid lumen', { exact: true })).toBeVisible()
    await page.getByRole('checkbox', { name: '전자 경로 보기', exact: true }).uncheck()
    await expect(page.getByTestId('electron-path')).toHaveCount(0)
    await expect(page.getByTestId('proton-path')).toHaveCount(1)
    await page.getByRole('button', { name: '01 H⁺ 기울기의 에너지', exact: true }).click()
    await page.getByRole('button', { name: '기울기 0', exact: true }).click()
    await expect(page.locator('.result-direction')).toHaveText('전기화학적 평형: 어느 방향에도 순 구동력이 없습니다.')
    await page.getByRole('slider', { name: 'A 구획의 pH', exact: true }).focus()
    await page.keyboard.press('ArrowRight')
    await expect(page.getByRole('slider', { name: 'A 구획의 pH', exact: true })).toHaveValue('7.1')
    await expect(page.locator('.result-direction')).toContainText('B → A')
    await noOverflow(page); await shot(page, `${size.width}-energy`)
    await page.getByRole('button', { name: '02 ATP 합성에 충분한가?', exact: true }).click()
    await expect(page.getByText('이 조건에서는 H⁺ 기울기만으로 ATP 합성을 구동하기 어렵습니다.', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: '기울기 조건 바꾸기', exact: true }).click()
    await page.getByRole('button', { name: '미토콘드리아 예시', exact: true }).click()
    await page.getByRole('button', { name: '02 ATP 합성에 충분한가?', exact: true }).click()
    await expect(page.getByText('이 조건에서는 H⁺ 기울기가 ATP 합성을 구동할 만큼 충분합니다.', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: '03 막을 조작하기', exact: true }).click()
    await page.getByRole('combobox', { name: '조건 B 처리', exact: true }).selectOption('leak')
    expect(Number(await page.getByLabel('B 산소 소비 · Oxygen consumption', { exact: true }).textContent())).toBeGreaterThan(100)
    expect(Number(await page.getByLabel('B 산화적 ATP 합성 속도', { exact: true }).textContent())).toBeLessThan(100)
    await noOverflow(page); await shot(page, `${size.width}-experiment`)
    await page.getByRole('combobox', { name: '조건 B 처리', exact: true }).selectOption('stopped')
    await expect(page.getByLabel('B 산소 소비 · Oxygen consumption', { exact: true })).toHaveText('0.0')
    await page.getByRole('button', { name: '04 어떤 설명이 자료와 맞는가?', exact: true }).click()
    await page.getByRole('button', { name: 'H⁺ 누출 증가', exact: true }).first().click()
    await expect(page.locator('.feedback')).toContainText('맞아요.')
    await page.getByRole('button', { name: '05 광합성으로 옮겨 보기', exact: true }).click()
    await noOverflow(page)
    await page.getByRole('link', { name: '학습 홈으로 →', exact: true }).click()
    await expect(page.locator('.completion')).toHaveText(['✓ 학습 확인 · ✓ 퀴즈 완료', '✓ 학습 확인 · ✓ 퀴즈 완료'])
    await page.reload()
    await expect(page.locator('.completion')).toHaveText(['✓ 학습 확인 · ✓ 퀴즈 완료', '✓ 학습 확인 · ✓ 퀴즈 완료'])
    expect(await page.evaluate(() => Object.keys(localStorage).sort())).toEqual(['photosynthesisQuizCompleted', 'photosynthesisViewed', 'respirationQuizCompleted', 'respirationViewed'])
    expect(errors).toEqual([])
  })
}
test('hash refresh, history, skip link, reduced motion and blocked storage', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.addInitScript(() => { Object.defineProperty(window, 'localStorage', { get: () => { throw new Error('Storage disabled') } }) })
  await page.goto('./#/photosynthesis')
  await page.reload()
  await expect(page.getByRole('heading', { level: 1 })).toContainText('광합성:')
  await page.getByRole('link', { name: '03화학삼투 탐색기', exact: true }).click()
  await page.goBack()
  await expect(page.getByRole('heading', { level: 1 })).toContainText('광합성:')
  await page.keyboard.press('Control+Home')
  await page.getByRole('link', { name: '본문으로 건너뛰기', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/#\/photosynthesis$/)
  await expect(page.locator('main')).toBeFocused()
  await page.getByRole('button', { name: '✓ 광합성 학습 확인', exact: true }).click()
  await expect(page.getByRole('button', { name: '✓ 학습 확인 완료', exact: true })).toBeVisible()
})
test('production counter import failure does not interrupt the app', async ({ page, baseURL }) => {
  const real = baseURL || ''
  if (!process.env.BASE_URL) {
    // Serve the built local app under its production origin, exercising the real
    // integration without sending an actual counter request.
    await page.route('https://suimaire.github.io/chemiosmosis-atp-explorer/**', async route => {
      const local = route.request().url().replace('https://suimaire.github.io/chemiosmosis-atp-explorer/', real)
      const response = await page.request.get(local)
      await route.fulfill({ response })
    })
  }
  await page.route('https://suimaire.github.io/assets/js/page-views.js', route => route.abort())
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('https://suimaire.github.io/chemiosmosis-atp-explorer/')
  await page.getByRole('link', { name: '탐색기로 바로 들어가기 →', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('화학삼투와 ATP 합성 탐색기')
  expect(errors).toEqual([])
})
